KTB-15 sending messages and refactoring code
flllmonova/KotlinTelegramBot pull request #13
Opened 2024-11-13 20:38 UTC by flllmonova

2024-11-14 13:25 UTC, dzenonce requested changes

2024-11-14 13:25 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +        val client: HttpClient = HttpClient.newBuilder().build()
HttpClient можно сделать полем TelegramBotService, чтобы не создавать экземпляр при каждом сетевом вызове.

2024-11-14 13:25 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +        val urlGetUpdates = "https://api.telegram.org/bot$botToken/getUpdates?offset=$updateId"
`https://api.telegram.org/bot` - можно вынести в константы

2024-11-14 13:25 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +    fun getLastUpdateId(updates: String): Int {
Лучше эти методы вынести из этого класса, чтобы он отвечал за выполнение запросов к telgram api, поскольку потом мы все равно будем мигрировать на способ сериализации данных

2024-11-14 13:25 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +        val lastUpdateIdRegex = "\"update_id\":(\\d+)".toRegex()
Еще хорошо бы вынести создание переменных за цикл, что бы они не пересоздавались при каждом вызове функций

2024-11-15 13:42 UTC, flllmonova commented on src/main/kotlin/TelegramBotService.kt
> +        val lastUpdateIdRegex = "\"update_id\":(\\d+)".toRegex()
а что происходит в памяти при пересоздании объекта?

2024-11-16 09:03 UTC, dzenonce commented on src/main/kotlin/TelegramBotService.kt
> +        val lastUpdateIdRegex = "\"update_id\":(\\d+)".toRegex()
При пересоздании у нас будет происходить создание нового объекта с выделением под него памяти в куче и вызов Garbage Collector для очистки памяти от неиспользуемого объекта, по сути, не пересоздавая объекты, мы оптимизируем работу программы, уменьшая количество вызовов GC и тем самым снижая нагрузку на устройство пользователя

2024-11-16 09:03 UTC, dzenonce approved these changes

2024-11-16 10:12 UTC, flllmonova commented on src/main/kotlin/TelegramBotService.kt
> +        val lastUpdateIdRegex = "\"update_id\":(\\d+)".toRegex()
Понятно, спасибо

2024-11-16 10:20 UTC, merged